services:
  - type: web
    name: portfolio-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        value: prajwalgaonkar24@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ORIGIN
        value: https://myportfolio-op-prajwal.vercel.app
    autoDeploy: true
    healthCheckPath: /
