services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        value: prajwalgaonkar24@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ORIGIN
        value: "*"
